### ISSUE TITLE
Device not discovered with certain name

### ISSUE THREAD

**Issue by MikeK97** [masmu/pulseaudio-dlna#228] opened 2016-07-13 22:18 UTC
I was having issues with discovering my Chromecast Audio. I could discover every other Chromecast and DLNA device on my network except this one. I tried some applications on my phone and they discovered this Chromecast Audio with no issues. After hours of trying to get it to work with _pulseaudio-dlna_ I decided to change the name of the device from _**Wharfedale Diamond 9.1**_ to _**Speakers**_. As soon as I did this the Chromecast Audio was found and worked as it should. I changed the name back to _**Wharfedale Diamond 9.1**_ to confirm it was an issue with the name, and sure enough the Chromecast Audio could not be found.

I'm not sure why this happened but I would guess it would have something to do with the numbers or period in the name?

**Comment by dermatthias** [comment] 2016-08-21 08:32
Had a similar problem. My Chromecast Audio device name had two dots in it (like "My. Device."), and zeroconf threw an error:

` raise Exception("Bad domain name at %s" % (off,))`

I think because of the dots in it it tried to handle it like a domain name or ip adress or something. I removed the dots and everything worked fine from then on.

**Comment by masmu** [comment] 2016-11-07 15:25
Sorry guys, I changed the name of my Chromecast to **Wharfedale Diamond 9.1** and also to **My. Device.**. But I was not able to reproduce that error. Maybe that was a bug in the Chromecast firmware which has been solved in the meantime?

**Comment by dermatthias** [comment] 2016-11-07 18:03
I can confirm masmu's comment. I cannot reproduce it either (as of today) with a device name like "My. Device.". Seems to be fixed on the Chromecast side. I got an update for my Chromecast Audio a few weeks ago, looks like that fixed it.

**Comment by masmu** [comment] 2016-11-07 18:31
So, I close this issue for now. If it reoccurs you guys can reopen it.

**Closed by masmu** 2016-11-07 18:31 UTC
Labels: bug
