### ISSUE TITLE
ubuntu 20.04 support

### ISSUE THREAD

**Issue by fabian727** [masmu/pulseaudio-dlna#399] opened 2020-04-17 13:17 UTC
I changed to Ubuntu20.04. Now pulseaudio-dlna is gone, because the master branch is still referencing python2.
[launchpad](https://answers.launchpad.net/ubuntu/+source/pulseaudio-dlna/+question/690014)

Is it possible to update the master branch for supporting python3 (which seems to already being supported).

It would be nice, if people like me could enjoy your work further on.
Thanks for all your work 'til here.

**Comment by polyzen** [comment] 2020-04-17 20:02
Duplicate of #262

**Closed as completed** 2020-04-20 17:39 UTC
