### ISSUE TITLE
Pulse audio can't start anymore

### ISSUE THREAD

**Issue by bozoo** [masmu/pulseaudio-dlna#291] opened 2017-04-01 14:57 UTC
Hi, 
My pulse audio doesn't work anymore :/
Any idea ? Here my debug.log [debug.log.txt](https://github.com/masmu/pulseaudio-dlna/files/887729/debug.log.txt)

**Comment by masmu** [comment] 2017-04-01 18:45
I guess it was working before... and that just stopped working by itself?

**Comment by bozoo** [comment] 2017-04-01 20:15
yes but i don't know why =P

**Comment by BaReinhard** [comment] 2017-04-03 06:18
I had a similar issue, it stopped working about 2 days ago. Tried apt-get install and the git version using make. Isn't working on Ubuntu mate.

**Comment by masmu** [comment] 2017-04-03 09:35
Same error? Could you please provide detailed OS information? I will setup a VM and try to reproduce the behavior.

**Comment by BaReinhard** [comment] 2017-04-03 13:36
I'll have to get that for you tonight, it ends in a critical error saying that pulseaudio is not running (when indeed it is, I have tried both as root and my normal user).

What struck me as odd was that this setup was working the day prior without an issue. No change. 

In the meantime I will get the OS info and then try a brand new installation on Ubuntu MATE see if anything changes.

**Comment by bozoo** [comment] 2017-04-03 20:05
Ubuntu 16.10
Linux 4.8.0-45-generic #48-Ubuntu SMP Fri Mar 24 11:46:39 UTC 2017 x86_64
x86_64 x86_64 GNU/Linux
Best,

2017-04-03 15:36 GMT+02:00 Brett Reinhard <notifications@github.com>:

**Comment by masmu** [comment] 2017-04-04 10:46
Just installed a fresh Ubuntu 16.10 VM. Couldn't reproduce the error, it is working here.

**Comment by masmu** [comment] 2017-04-04 12:09
I guess I found the bug. It happens when you have a non-ascii character in your path. Could you both please test that [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/diskutils-encoding) which contains the fix?

**Comment by bozoo** [comment] 2017-04-04 19:51
Hi,
Great job ! The problem is solved with this branch !
Thank's ;)

2017-04-04 14:09 GMT+02:00 Massimo Mund <notifications@github.com>:

**Comment by BaReinhard** [comment] 2017-04-04 22:15
Here is the issues I am having:


pulseaudio-dlna run as user
https://gist.github.com/BaReinhard/0f40461b3245ccbf13308441d36b15c0

pulseaudio-dlna run as root
https://gist.github.com/BaReinhard/f6a6fa7fa0cae44d5fe50821d905aa20

contents of `/etc/*-release` file:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by BaReinhard** [comment] 2017-04-04 22:24
I did also notice this when installing the new version:

```
brett@brett:~/pulseaudio-dlna-bug-diskutils-encoding$ sudo make
virtualenv --system-site-packages -p python2.7 .
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/brett/pulseaudio-dlna-bug-diskutils-encoding/bin/python2.7
Also creating executable in /home/brett/pulseaudio-dlna-bug-diskutils-encoding/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
bin/pip install --editable . && touch pulseaudio_dlna.egg-info
The directory '/home/brett/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/brett/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/brett/pulseaudio-dlna-bug-diskutils-encoding
Requirement already satisfied: docopt>=0.6.1 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: requests>=2.2.1 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: setproctitle>=1.0.1 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: protobuf>=2.5.0 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: notify2>=0.3 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: psutil>=1.2.1 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: futures>=2.1.6 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: chardet>=2.0.1 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: netaddr>=0.7.18 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: netifaces>=0.8 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: lxml>=3 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: zeroconf>=0.17 in /usr/lib/python2.7/dist-packages (from pulseaudio-dlna==0.5.2)
Requirement already satisfied: enum-compat in /usr/local/lib/python2.7/dist-packages/enum_compat-0.0.2-py2.7.egg (from zeroconf>=0.17->pulseaudio-dlna==0.5.2)
Requirement already satisfied: six in ./lib/python2.7/site-packages (from zeroconf>=0.17->pulseaudio-dlna==0.5.2)
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from enum-compat->zeroconf>=0.17->pulseaudio-dlna==0.5.2)
Installing collected packages: pulseaudio-dlna
  Found existing installation: pulseaudio-dlna 0.5.2
    Not uninstalling pulseaudio-dlna at /usr/local/lib/python2.7/dist-packages/pulseaudio_dlna-0.5.2-py2.7.egg, outside environment /home/brett/pulseaudio-dlna-bug-diskutils-encoding
  Running setup.py develop for pulseaudio-dlna
Successfully installed pulseaudio-dlna
```

**Comment by masmu** [comment] 2017-04-05 09:10
@BaReinhard I am sure you guys don't have the same problem. 

Furthermore it is hard for me to get an idea of what you were doing without the commands you were executing. What I can say is, that `sudo make` is wrong. A development version is just being installed locally in a python virtual env. That means that nothing is installed globally and once you are done with the dev version you can simply delete the folder. Because really everything is in there and as I said nothing was installed globally. Thats the beauty of python's virtual envs.

So, try the following:
```bash
# Install the dependecies (most of them should already be installed)
    sudo apt-get install \
        python2.7 \
        python-pip \
        python-setuptools \
        python-dbus \
        python-docopt \
        python-requests \
        python-setproctitle \
        python-gi \
        python-protobuf \
        python-notify2 \
        python-psutil \
        python-concurrent.futures \
        python-chardet \
        python-netifaces \
        python-netaddr \
        python-lxml \
        python-zeroconf \
        vorbis-tools \
        sox \
        lame \
        flac \
        opus-tools \
        pavucontrol \
        virtualenv python-dev git-core
# Clone the project
    git clone https://github.com/masmu/pulseaudio-dlna.git ~/pulseaudio-dlna
    cd ~/pulseaudio-dlna
# Checkout a specific branch (optional, since the fix does not apply to your problem)
    git checkout bug/diskutils-encoding
# Make it runnable
    make
# Run it
    bin/pulseaudio-dlna
```
So, I would suggest you to also try this [branch](https://github.com/masmu/pulseaudio-dlna/pull/284).
```bash
   cd ~/pulseaudio-dlna
# Remove the development files and the python virtual env
   make clean
# Get the bug/per-user-dbus-socket branch
   git checkout bug/per-user-dbus-socket
# Make it runnable again
   make
# Run it
   bin/pulseaudio-dlna
```

**Comment by masmu** [comment] 2017-04-06 10:09
@BaReinhard I removed both branches and merged them into master. So please just leave out the `git checkout` commands.

**Comment by BaReinhard** [comment] 2017-04-06 14:59
Thank you, still haven't had a chance to test it, but this weekend I will for sure. Do you happen to know how often the Debian sources are update to reflect the master branch here?

**Comment by masmu** [comment] 2017-04-06 15:05
@BaReinhard , I am not sure. [muammar](https://github.com/muammar) can tell for sure. He is the maintainer of the debian package.

But I guess several months ...

**Comment by muammar** [comment] 2017-04-06 15:17
@masmu @BaReinhard I only upload stable versions to Debian archive, but I have no problems uploading git versions. Would you like it to be the case?. Just let me know and I will prepare a new upload this weekend.

**Comment by BaReinhard** [comment] 2017-04-06 16:03
@muammar sorry for my ignorance but would you mind explaining what you mean by uploading git versions and ultimately what that means in terms of the Debian archive?

Thank you @masmu

**Comment by muammar** [comment] 2017-04-06 16:09
@BaReinhard I will rephrase it: I can upload master's snapshots as the source to debian archive. The only drawback would be that if a new file has been added, then the package has to pass by [FTP NEW queue](https://ftp-master.debian.org/new.html) to check if license stuff is fine. I have decided to upload a new version this weekend using the latest version at master.

**Comment by muammar** [comment] 2017-04-07 01:25
I went ahead and uploaded a [new version](https://buildd.debian.org/status/package.php?p=pulseaudio-dlna&suite=sid).

**Comment by BaReinhard** [comment] 2017-04-07 03:25
@muammar thank you it is much appreciated! I will test it out this coming weekend (I am assuming things will work great).

**Comment by BaReinhard** [comment] 2017-04-07 19:49
I got a change to try it, tried with the latest debian resource, as well as the master branch. Still getting the following errors:

```
bin/pulseaudio-dlna 
04-07 12:48:29 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
04-07 12:48:29 pulseaudio_dlna.application                    INFO     Using version: 0.5.2+git-b6313819028d147e8b29af9cb58a601c83d3193c (master)
04-07 12:48:29 pulseaudio_dlna.application                    INFO     Binding to *:8080
04-07 12:48:29 pulseaudio_dlna.application                    INFO     Encoder settings:
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
04-07 12:48:29 pulseaudio_dlna.application                    INFO     Codec settings:
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="1" mime_type="audio/L16" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
04-07 12:48:29 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
Failure: Module initialization failed
04-07 12:48:29 pulseaudio_dlna.pulseaudio                     CRITICAL PulseAudio seems not to be running or PulseAudio dbus module could not be loaded. The application cannot work properly!
04-07 12:48:36 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()
```

**Comment by masmu** [comment] 2017-04-07 20:05
There is some problem with your pulseaudio.
Did you change some pulseaudio configuration? What gives you `ps aux | grep -i pulseaudio`?

**Comment by BaReinhard** [comment] 2017-04-07 20:05
i found the fix it was one of two steps:
but I believe this to be the fix
```
mv ~/.config/pulse ~/.config/pulse.bad 
```

**Comment by masmu** [comment] 2017-04-07 20:09
This resets your pulseaudio config, because you moved the current one to a location where pulseaudio cannot find it anymore.

**Comment by BaReinhard** [comment] 2017-04-07 20:10
i meant to paste something else so I updated my post, .config/pulse was empty, so I don't believe that was the issue

**Comment by masmu** [comment] 2017-04-07 20:12
Is it now still empty? Maybe the rights for that folder aren't correct.
What gives you `ls -l ~/.config/pulse.bad`

**Comment by BaReinhard** [comment] 2017-04-07 20:23
```
brett@brett:~$ ls -l ~/.config/pulse.bad
total 48
-rw-r--r-- 1 brett brett 12288 Apr  7 12:06 b450c14dd93941a3a6c451bf8610560d-card-database.tdb
-rw-r--r-- 1 brett brett    45 Apr  7 12:50 b450c14dd93941a3a6c451bf8610560d-default-sink
-rw-r--r-- 1 brett brett    53 Apr  7 12:50 b450c14dd93941a3a6c451bf8610560d-default-source
-rw-r--r-- 1 brett brett 12288 Apr  7 12:06 b450c14dd93941a3a6c451bf8610560d-device-volumes.tdb
-rw-r--r-- 1 brett brett 12288 Apr  7 12:11 b450c14dd93941a3a6c451bf8610560d-stream-volumes.tdb
-rw------- 1 brett brett   256 Apr  7 12:06 cookie
brett@brett:~$ ls -l ~/.config/pulse
total 48
-rw-r--r-- 1 brett brett 12288 Apr  7 13:00 b450c14dd93941a3a6c451bf8610560d-card-database.tdb
-rw-r--r-- 1 brett brett    45 Apr  7 13:09 b450c14dd93941a3a6c451bf8610560d-default-sink
-rw-r--r-- 1 brett brett    53 Apr  7 13:09 b450c14dd93941a3a6c451bf8610560d-default-source
-rw-r--r-- 1 brett brett 12288 Apr  7 13:00 b450c14dd93941a3a6c451bf8610560d-device-volumes.tdb
-rw-r--r-- 1 brett brett 12288 Apr  7 13:13 b450c14dd93941a3a6c451bf8610560d-stream-volumes.tdb
-rw------- 1 brett brett   256 Apr  7 12:59 cookie
brett@brett:~$ 
```
here is the output of both

so I made a mistake and thought pulse was a file and not a directory 👎 .

What's odd is that this was on a fresh installation of ubuntu, im guessing that the ~/.config/pulse had some bad configuration.

So to clear up my previous mistake, what did fix it was 

```
mv ~/.config/pulse ~/.config/pulse.bad
```

**Comment by masmu** [comment] 2017-04-07 20:25
I guess it was the `audio` group. [link](https://wiki.ubuntu.com/Audio/TheAudioGroup)
> As a practical rule of thumb for Debian and Ubuntu systems, there should be no users in the audio group. 

> Exceptions
When you want a user to be able to access a sound card even if he is not logged in.
When you're running a system-wide daemon that is never logged in but still needs sound card access
When you're running an old, now unsupported version of Ubuntu which does not have proper ConsoleKit integration (TODO: Look up and specify which versions of Ubuntu that is.)
If you're running Jackd and need realtime privileges (see below)

**Comment by BaReinhard** [comment] 2017-04-07 20:55
I've since removed my user from both lp and audio, and dlna runs properly each time.

**Comment by masmu** [comment] 2017-04-07 20:59
Good to hear and thanks for mentioning it. Hopefully I will remember it some time later when someone else is running into that problem.

**Comment by BaReinhard** [comment] 2017-04-07 21:04
No problem, and thank you for the help and guidance.

**Comment by masmu** [comment] 2017-04-07 21:18
You are welcome!

**Closed** 2017-04-07 21:18 UTC
