### ISSUE TITLE
pulseaudio-dlna command changes my default device

### ISSUE THREAD

**Issue by cafaia** [masmu/pulseaudio-dlna#366] opened 2018-11-30 15:07 UTC
When I run the pulseaudio-dlna command my default device is changed to an output dlna, what should I do to prevent this?
I recently had to reset my settings and this problem started to appear, but I did not have it before.
Thank you all!

**Comment by geotom** [comment] 2018-12-14 13:37
Same here on Linux Mint. Quite annoying.As soon as a new device is coming up, pulseaudio-dlna sets this is a new output. Maybe not the fault of pulseaudio-dlna, but pulseaudio itself?

**Comment by cafaia** [comment] 2018-12-14 18:05
Hi, wandth!

Yes, maybe it is an error in pulseaudio and not in pulseaudio-dlna, but I tried various settings in pulseaudio and nothing.
I'm using version 11.1 of pulseaudio and I use Gentoo.

**Comment by geotom** [comment] 2018-12-14 19:41
Do you start pulseaudio-dlna manually?

**Comment by cafaia** [comment] 2018-12-14 19:50
Yes, I start manually, because I only run it when I have the TV on.

**Comment by masmu** [comment] 2019-02-09 12:20
This seems to be a pulseaudio issue and it is annoying for me as well. As soon as I create a new sink pulseaudio (probably some pulseaudio module) changes the default sink to that. 

Maybe someone can have a look at that and find out which of the modules produces that behavior. `pacmd list modules` and `pacmd unload-module <module-name>`

**Comment by ehoitinga** [comment] 2019-02-09 12:37
I already tried to edit /etc/pulse/default.pa and add the lines:
```
### Make some devices default
set-default-sink output alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
set-default-source input alsa_input.pci-0000_00_1f.3.analog-stereo
```
But this did not help. The last detected DLNA sink is set to the default when starting pulseaudio-dlna. I will try to find which module is responsable for this.

Erik

**Comment by polyzen** [comment] 2019-02-09 21:42
I had an issue where Pulse kept switching audio to HDMI until I commented out `load-module module-switch-on-port-available` in `/etc/default.pa`. I'm not having this problem with pulseaudio-dlna, so perhaps you want to try unloading that module.

**Comment by masmu** [comment] 2019-02-10 00:10
For me the behavior stops once unloading `module-switch-on-connect`.
So, unload the module (`pacmd unload-module module-switch-on-connect`), set your default sink again and launch `pulseaudio-dlna`. See if that helps.

**Comment by masmu** [comment] 2019-02-10 00:27
And [here](https://lists.freedesktop.org/archives/pulseaudio-discuss/2017-November/029088.html) is the confirmation. In pulseaudio 12 this behavior can be fixed by loading the module like:
```bash
pacmd unload-module module-switch-on-connect
pacmd load-module module-switch-on-connect ignore_virtual=yes
``` 

But that additional flag doesn't exist for prior versions. So, I guess just unloading the module helps.

**Comment by ehoitinga** [comment] 2019-02-10 10:11
Came to the same conclusion this morning. When unloading this module before starting pulseaudio-dlna, my laptop keeps the internal speaker as default sink. However in Linux mint 19.0 and also 19.1, version 11.1 of pulseaudio is used so I can't use the option ignore_virtual=yes

```
erik@LAPTOP-ERIK:~$ pulseaudio -v
I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: This is PulseAudio 11.1
I: [pulseaudio] main.c: Page size is 4096 bytes
I: [pulseaudio] main.c: Machine ID is ef635a010d284bc38d762d2b9f0e65ac.
I: [pulseaudio] main.c: Session ID is c2.
I: [pulseaudio] main.c: Using runtime directory /run/user/1000/pulse.
I: [pulseaudio] main.c: Using state directory /home/erik/.config/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-11.1/modules.
I: [pulseaudio] main.c: Running in system mode: no
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
```
```
erik@LAPTOP-ERIK:~$ pacmd load-module module-switch-on-connect ignore_virtual=yes
Module load failed.
erik@LAPTOP-ERIK:~$
```
The problem with Mint is that it relies on Ubuntu as base system and therefore Ubuntu version jumps are taking quit a lot of time. The Ubuntu version used in Mint 19.0 and 19.1 is bionic (18.04 LTS) and makes use of pulseaudio version 11.1. As of Ubuntu cosmic (18.10) version 12.2 of pulseaudio is introduced. I don't know when Linux Mint will jump to this Ubuntu version. I can also switch to Fedora 29 where version 12.2 of pulseaudio is used.

For now in /etc/pulse/default.pa I changed the lines:
```
### Use hot-plugged devices like Bluetooth or USB automatically (LP: #1702794)
.ifexists module-switch-on-connect.so
load-module module-switch-on-connect
.endif
```
into
```
### Use hot-plugged devices like Bluetooth or USB automatically (LP: #1702794)
#.ifexists module-switch-on-connect.so
#load-module module-switch-on-connect
#.endif
```

To stop this module from loading at a reboot.

Erik

**Comment by masmu** [comment] 2019-02-10 16:02
Yes, you are right. Disabling the module is also my way to go.

**Comment by geotom** [comment] 2019-02-11 12:03
Thx for the feedback - I had pulseaudio-dlna disabled because of this recent behaviour. Hope the distro-upgrade to pulseaudio 12 comes soon

**Comment by ehoitinga** [comment] 2019-02-11 17:59
> Thx for the feedback - I had pulseaudio-dlna disabled because of this recent behaviour. Hope the distro-upgrade to pulseaudio 12 comes soon

The newest version of Linux Mint 19.1 is still on pulseaudio 11.1 because it relies on Ubuntu 18.04 LTS which has pulseaudio 11.1. Same goes for Gentoo and other Ubuntu derivatives. Was thinking about moving to Fedora which has pulseaudio 12.2 and a far more newer kernel and in general far more recent version of other pre-installed software packages and is more stable than Mint, etc, etc.

But Fedora does not support desktop, that is placing items on the desktop and this is a big deal-breaker for me. Sorry for being a bit off-topic.

As said, disabling the module does the trick. I have not encountered any drawbacks in doing this.

**Comment by Cygn** [comment] 2019-02-12 08:48
@ehoitinga 
> But Fedora does not support desktop, that is placing items on the desktop and this is a big deal-breaker for me. Sorry for being a bit off-topic.

**//offtopic**
This is to get desktop icons on gnome 3:
https://extensions.gnome.org/extension/1465/desktop-icons/

Cinnamon is also available  on Fedora
https://fedoraproject.org/wiki/Cinnamon

(doing my bit of Fedora evangilsm :smile:  )

**Comment by ehoitinga** [comment] 2019-02-14 21:20
OK,

On fedora 29 I am on` pulseaudio version 12.2` and in its ` /etc/pulse/default.pa` file the module `module-switch-on-connect` is not even loaded. So the problem mentioned here is solved out of the box.

I can confirm the `pacmd load-module module-switch-on-connect ignore_virtual=yes` command also works. Default device stays on laptop speaker.

Erik

**Comment by masmu** [comment] 2019-02-21 14:18
So I guess this is resolved.

**Closed as completed by masmu** 2019-02-21 14:18 UTC
