### ISSUE TITLE
Raumfeld Speaker refuses to play: no suitable codec found

### ISSUE THREAD

**Issue by robert7k** [masmu/pulseaudio-dlna#219] opened 2016-06-07 09:52 UTC
Raumfeld Speakers refuse to play through pulseaudio-dlna-0.5.2

Here's the relevant log output:

```
06-07 11:50:55 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Kitchen (DLNA)" to play ...
06-07 11:50:55 pulseaudio_dlna.plugins.renderer               INFO     There was no suitable codec found for "Kitchen (DLNA)". The device can play "". Install one of following encoders: "".
06-07 11:50:55 pulseaudio_dlna.pulseaudio                     ERROR    The device "Kitchen (DLNA)" failed to play! (500) - Could not find a suitable encoder!
```

The problem appears since I updated the Raumfeld firmware to version 1.55.

I experienced a similar problem with the Android App "BubbleUPnP". However, I could resolve this by enabling a setting "Disable Mime-type check", which ignores the list of supported codecs. Maybe pulseaudio-dlna should provied a similar option as well?

**Comment by masmu** [comment] 2016-09-23 14:26
Wow! The device really does not accept any mime types? That is odd... Ok, I will add that flag in the next release.

**Comment by robert7k** [comment] 2016-09-23 14:35
In the meantime I also found a workaround to use pulseaudio-dlna with Raumfeld speakers: in ~/.local/share/pulseaudio-dlna/devices.json I added codes to the Raumfeld devices:

```
        "codecs": [
            {
                "rules": [],
                "bit_rate": null,
                "identifier": "mp3", 
                "mime_type": "audio/mpeg"
            }, 
            {
                "rules": [], 
                "identifier": "wav", 
                "mime_type": "audio/x-wav"
            }, 
            {
                "rules": [], 
                "identifier": "flac", 
                "mime_type": "audio/x-flac"
            }
```

**Comment by masmu** [comment] 2016-09-23 14:41
Yeah, that way you are fooling the mime type system.
Very creative! One should do the job though. Like:
```
        "codecs": [
            {
                "rules": [],
                "bit_rate": null,
                "identifier": "mp3", 
                "mime_type": "audio/mpeg"
            }
        ]
```

**Comment by Siilwyn** [comment] 2016-10-03 15:46
Thank you for posting the workaround! I had the same issue and this solved it for me.

**Comment by masmu** [comment] 2016-11-07 14:31
I just created the promised [feature](https://github.com/masmu/pulseaudio-dlna/tree/feature/ignore-mime-types) to disable the mime type check. Feel free to test it.

**Comment by svenfoo** [comment] 2017-02-10 16:10
Found the cause of the problem today and it should be fixed on the Raumfeld devices with the next Raumfeld firmware update.

**Closed** 2017-03-14 23:05 UTC
Labels: enhancement
